### ISSUE TITLE
Axis Confusion Between TargetCartPos & CartPos 

### ISSUE THREAD

**Issue by c53wei** [Mecademic/mecademicpy#11]
Hi there

I am running a simple experiment by rotating joint 6 through (0, -90, -180, 90, 0) whilst keeping all other angles at 0 and recording the following fields with the Robot class' FileLogger: ["TargetCartPos", "CartPos", "TargetCartVel", "CartVel"].

However, it appears that euler angles about the x and z axis (α , γ) of the measured cartesian position become swapped, as shown in the right column of the attached figure: 
![axis_switching](https://user-images.githubusercontent.com/55329592/224410046-f8f73044-fdfb-4f93-9d12-258d62707d66.png)
** Note that the deviation between +/-180 in measured γ is fine, they're the same.

I initially thought that I misunderstood their outputs--perhaps the co-ordinate frames of the target and measured are different. However, the same plot comparing "TargetCartVel" and "CartVel" does not exhibit this axis swapping behaviour: 
![velocity](https://user-images.githubusercontent.com/55329592/224412264-43e45c2d-93af-41db-9c07-adab6fbe29be.png)

So, I was hoping that an issue can be raised so that I may understand what is going on and make changes accordingly (whether it's a user issue of a bug).

Let me know if a copy of the python script, outputted .csv, and/or json trajectory sequence would be of use.

Thank you!!

**Comment by gbmecademic** [comment]
Hello,
The swapping in the position angle is normal when reading the measured pose. This is because when dealing with the Euler angles, multiple solutions can give the same orientation when dealing with 90° rotations. The measured pose uses the encoder feedback to find the pose and because of encoder resolution and numerical innacuracies, it is possible to see a jump in the values when at a multiple of 90° angle. The target pose is the commanded pose of the robot so it will be stable.

As for the velocity, since it is not related to the Euler angles, it will always be stable (as we will not see a big jump like with the position). It is not subject to the same mathematical constraints. The velocity is a vector of rotation with its magnitude being the speed.

Hope this helps.

**Comment by gbmecademic** [comment]
Hello again,
I'm following up to see if I can close this issue or if you needed more information.

**Comment by c53wei** [comment]
Hi Gabriel

Thank you for your detailed clarification, please close the issue!

On Mar 14, 2023, at 10:56 AM, Gabriel Boucher ***@***.***> wrote:

﻿

Hello again,
I'm following up to see if I can close this issue or if you needed more information.
